### ISSUE TITLE
Melhoria - 1 - cliente/associa-conta-cliente e fornecedor/associa-conta-fornecedor: não dá retorno após processamento da página

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#11]
Após processamento, a página não permanece exatamente a mesma, à exceção do discretíssimo log de mensagens. Não é o suficiente para o usuário perceber que o pedido foi processado com sucesso.

![image](https://user-images.githubusercontent.com/42449573/55748916-323ab780-5a16-11e9-91e2-3ad45c5e0826.png)

**Comment by marcioonodera** [comment]
Incluindo tela de fornecedor 

![image](https://user-images.githubusercontent.com/42449573/55755503-8a2cea80-5a25-11e9-9f76-c24748c868bd.png)

**Comment by marcioonodera** [comment]
Sugestão seria redirecionar para /sociedade/dash-empresas

**Comment by suzigit** [comment]
Incluído o redirecionamento
