### ISSUE TITLE
Bug - 1 - bndes/val-cadastro: não reconhece conta BNDES

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#12]
Ao tentar Validar ou Invalidar, mostra notificação de que é necessário que o Metamask esteja gerenciando a conta do BNDES, mesmo com a conta do BNDES selecionada. Pode estar relacionado ao Issue#9, que está mostrando como Disponível a conta do BNDES.

![image](https://user-images.githubusercontent.com/42449573/55751611-7466f780-5a1c-11e9-9537-40a83d10b8f5.png)

**Comment by josenogueiradalmeida** [comment]
Interesting bug! It does not happen in localhost env. 
![image](https://user-images.githubusercontent.com/42451402/55757770-45a44d80-5a2b-11e9-845d-ec6be2a1a82f.png)

**Comment by josenogueiradalmeida** [comment]
Closing the issue. My test was OK with two accounts. Please review and reopen if it is not OK.

**Comment by marcioonodera** [comment]
No teste, validou cadastro de fornecedor, mas o problema continua para validar/invalidar cliente, no caso o segundo subcrédito (1A).

![image](https://user-images.githubusercontent.com/42449573/55885344-28cd5e80-5b80-11e9-902f-fec031469ad2.png)

**Comment by marcioonodera** [comment]
Nova tentativa para invalidação foi bem sucedida. Sem motivação clara.

**Comment by marcioonodera** [comment]
Na verdade, aparentemente quando se troca a conta no Metamask, a página não captura essa informação. Deveria ter um tipo "reload" na página, para fazer nova leitura da conta Metamask.

**Comment by suzigit** [comment]
Resolvido reload da conta
