### ISSUE TITLE
Bug - 1 - cliente/associa-conta-cliente: novos cadastros com conta Validada, conta invalidada e para subcédito já associado no cadastro foram enviadas para blockchain

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#15]
Cadastro com conta Validada foi enviada para blockchain e deu erro posterior na blockchain. Entendo que nem deveria nem ser enviada.

![image](https://user-images.githubusercontent.com/42449573/55888447-be1f2180-5b85-11e9-82f2-42fef13fb3b9.png)

**Comment by marcioonodera** [comment]
novo cadastro com conta Validada e também com conta previamente invalidada no cadastro  foi enviada para blockchain. Entendo que nem deveria nem ser enviada.

![image](https://user-images.githubusercontent.com/42449573/55888706-41407780-5b86-11e9-9cd7-703470c3c1f2.png)

**Comment by marcioonodera** [comment]
Novos cadastros com:
1. conta previamente Validada
2. conta previamente invalidada
3. subcrédito que já tinha conta associada

...no cadastro foram enviadas para blockchain. Entendo que nem deveriam ser enviadas.

![image](https://user-images.githubusercontent.com/42449573/55888866-86fd4000-5b86-11e9-8666-89cdf670f0ee.png)

**Comment by marcioonodera** [comment]
(...)
3. subcrédito que já tinha conta associada: nos casos em que já há conta validada associada a subcrédito, creio que este nem deveria aparecer nas opções da caixa drop-down. Somente na opção de troca de conta.

**Comment by suzigit** [comment]
Não é mais enviado. 
Caixa drop-down tb não apresenta mais subcréditos já associados
