### ISSUE TITLE
Bug - 1 - cliente/associa-conta-cliente: não é possível associar nova conta blockchain a subcrédito que já teve conta invalidada

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#16]
Erros seguidos sem causa preliminar para associar nova conta blockchain a um subcrédito que teve uma conta anteriormente invalidada.

![image](https://user-images.githubusercontent.com/42449573/55889562-9e88f880-5b87-11e9-8d12-c0c79a31e2db.png)

**Comment by suzigit** [comment]
Ajustado
