### ISSUE TITLE
Bug - 2 - /cliente/consulta-transferencia: página não está funcional

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#23]
1. Não consegui utilizar a página.
2. Não apresenta nenhum resultado e não é possível alterar o fornecedor desejado, ou visualizar lista de fornecedores disponíveis.
3. Mesmo mudando a conta Metamask, os dados nos campos cinza não se alteram. Não há botão de atualização da conta Metamask na tela.
4. Botão próximo não leva a nada nessas condições. 

![image](https://user-images.githubusercontent.com/42449573/55978545-64425880-5c66-11e9-8da5-0aa4d5b78477.png)

**Comment by suzigit** [comment]
Decidir o que fazer com essa funcionalidade

**Comment by vanessaalm** [comment]
Funcionalidade retirada do escopo do piloto.
