### ISSUE TITLE
Cliente: Associar: não reconhece conta BNDES como indisponível

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#5]
Nessa tela, entendo que ao colocar a conta BNDES no metamask, ele deveria acusar que essa conta está indisponível. Mas ela diz que a conta está Disponível, mesmo após refresh.

![image](https://user-images.githubusercontent.com/42449573/53663862-a929a700-3c45-11e9-9ec8-33543d9b6dd9.png)

**Comment by suzigit** [comment]
Resolvido.
