### ISSUE TITLE
Bug - 1 - cliente/associa-conta-cliente e fornecedor/associa-conta-fornecedor: mostra conta indisponível como disponível

### ISSUE THREAD

**Issue by marcioonodera** [bndes/bndestoken#9]
Ao selecionar conta blockchain do BNDES no metamask, sistema aponta conta como "Disponível"

![image](https://user-images.githubusercontent.com/42449573/55747918-bb9cba80-5a13-11e9-9b4e-6a5952e076c4.png)

**Comment by marcioonodera** [comment]
Incluída tela fornecedor/associa-conta-fornecedor

![image](https://user-images.githubusercontent.com/42449573/55754301-b6933780-5a22-11e9-936d-068b5b210012.png)

**Comment by suzigit** [comment]
Alterei para retornar "Conta Reservada - BNDES"
Além disso, caso acesse com a conta da ANCINE, retornará  "Conta Reservada - Liquidante do contrato"
